name: Chimera
options:
  bundleIdPrefix: com.baboo
  xcodeVersion: "15.0"
targets:
  Chimera:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: Chimera
    dependencies:
      - framework: Frameworks/MoltenVK.xcframework
        embed: true
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.baboo.chimera
      INFOPLIST_FILE: Chimera/Info.plist
      GENERATE_INFOPLIST_FILE: NO
      LIBRARY_SEARCH_PATHS: $(inherited) $(PROJECT_DIR)/Frameworks
      OTHER_LDFLAGS: $(inherited) -lFEXCore -lsqlite3 -lz
      ENABLE_BITCODE: NO
      SWIFT_VERSION: 5.0
