name: Chimera
options:
  bundleIdPrefix: com.baboo
  xcodeVersion: "15.0"
  deploymentTarget:
    iOS: "16.0"
targets:
  Chimera:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - Chimera
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.baboo.chimera
      INFOPLIST_FILE: Chimera/Info.plist
      GENERATE_INFOPLIST_FILE: NO
      # Force the project file format to be compatible with Xcode 15.4
      LastUpgradeCheck: "1500"
