name: Chimera
options:
  xcodeVersion: "15.0" # This fixes the 'Future Format' error
targets:
  Chimera:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - Chimera
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.baboo.chimera # Change this to something unique
      INFOPLIST_FILE: Chimera/Info.plist
      GENERATE_INFOPLIST_FILE: NO
