name: Chimera Cloud Build
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - name: Install XcodeGen
        run: brew install xcodegen

      - name: Generate Project
        run: xcodegen generate

      - name: Fix Compatibility
        # This command forces the project file to be readable by older Xcode versions
        run: |
          sed -i '' 's/objectVersion = [0-9]*/objectVersion = 54/g' Chimera.xcodeproj/project.pbxproj

      - name: Build IPA
        run: |
          xcodebuild -project Chimera.xcodeproj \
                     -scheme Chimera \
                     -configuration Release \
                     -sdk iphoneos \
                     archive -archivePath Chimera.xcarchive \
                     CODE_SIGNING_ALLOWED=NO \
                     CODE_SIGNING_REQUIRED=NO
