name: Chimera Cloud Build
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: brew install xcodegen cmake

      - name: Unzip MoltenVK
        run: |
          cd Frameworks
          unzip MoltenVK.xcframework.zip
          # We keep it organized for the compiler
          rm MoltenVK.xcframework.zip
          cd ..

      - name: Build FEX Core
        run: |
          git clone --recurse-submodules https://github.com/FEX-Emu/FEX.git
          cd FEX
          mkdir Build && cd Build
          # Compiling FEX for iOS ARM64
          cmake .. -DCMAKE_SYSTEM_NAME=iOS -DCMAKE_OSX_ARCHITECTURES=arm64 -DBUILD_TESTING=OFF
          make -j$(sysctl -n hw.ncpu) FEXCore
          cp libFEXCore.a ../../Frameworks/

      - name: Generate and Build
        run: |
          xcodegen generate
          # Fix Xcode project versioning
          sed -i '' 's/objectVersion = [0-9]*/objectVersion = 54/g' Chimera.xcodeproj/project.pbxproj
          
          xcodebuild -project Chimera.xcodeproj \
                     -scheme Chimera \
                     -configuration Release \
                     -sdk iphoneos \
                     archive -archivePath Chimera.xcarchive \
                     CODE_SIGNING_ALLOWED=NO \
                     CODE_SIGNING_REQUIRED=NO
